name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install dependencies
    - name: Install SDL2 libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-gfx-dev

    # Step 3: Compile the program
    - name: Compile
      run: make
    
    # Step 4: Upload the binary
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: spaceshooter
        path: spaceshooter