name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          # Additional configuration for each OS
          - os: ubuntu-latest
            sdl-install: "sudo apt-get update && sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-gfx-dev"
          - os: windows-latest
            sdl-install: "choco install sdl2 sdl2_ttf sdl2_gfx"

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install SDL2 libraries
        run: ${{ matrix.sdl-install }}

      # Step 2.1: Verify SDL2 installation
      - name: Verify SDL2 installation
        run: |
          ls /usr/include/SDL2 || dir C:\\SDL2

      # Step 3: Compile the program
      - name: Compile
        run: make

      # Step 4: Debug directory contents
      - name: Debug directory contents
        run: ls -R || dir /s  # List files (works on both Unix and Windows)

      # Step 5: Upload the compiled binary
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spaceshooter-binary-${{ matrix.os }}
          path: spaceshooter